//PIPS generated variable
P4A_accel_kernel p4a_kernel_main(int i, float *a, float *b, int n);
//
//     This module was automatically generated by PIPS
//
;
//PIPS generated variable
P4A_accel_kernel_wrapper p4a_wrapper_main(int i, float *a, float *b, int n);
