//PIPS generated variable
P4A_accel_kernel p4a_kernel_main_1(int i, float *a, float *b, float *c, int n);
//
//     This module was automatically generated by PIPS
//
;
//PIPS generated variable
P4A_accel_kernel_wrapper p4a_wrapper_main_1(int i, float *a, float *b, float *c, int n);
